apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello-world.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hello-world.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "shru2001/node-hello-world:latest"
          imagePullPolicy: IfNotPresent  # Adjust this policy based on your deployment strategy
          ports:
            - name: http
              containerPort: 3000  # Adjust based on the port your application listens on
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"   # Adjust based on your application's needs
              cpu: "100m"       # Adjust based on your application's needs
            limits:
              memory: "256Mi"   # Adjust based on your application's needs
              cpu: "250m"       # Adjust based on your application's needs
          livenessProbe:
            httpGet:
              path: /           # Adjust if your application has a specific health check endpoint
              port: http        # Match the containerPort defined above
            initialDelaySeconds: 30   # Adjust based on your application startup time
            periodSeconds: 10         # Adjust based on your application's expected behavior
          readinessProbe:
            httpGet:
              path: /           # Adjust if your application has a specific readiness check endpoint
              port: http        # Match the containerPort defined above
            initialDelaySeconds: 5    # Adjust based on your application startup time
            periodSeconds: 10     
