apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  type: NodePort  # Exposes the service on each Node’s IP at a static port
  ports:
    - protocol: TCP
      port: 80  # Port exposed on the service
      targetPort: 3000  # Port on the container where the application listens
      name: http
  selector:
    {{- include "hello-world.selectorLabels" . | nindent 4 }}
